### PR TITLE
Added paramater to get output as json

### PR DESCRIPTION
**Pull request by Artmann**

### CODE REVIEW

**Comment by jrepp** [comment]
I created a branch using your technique and rolled some additional structural improvements in as well. 

There are a few issues with filtering through pretty printer where it adds quotes and tries to prettyfy the JSON. The Python JSON library has this functionality built in so I'd like to emit well-formed JSON using a slightly different path in the code.

One issue I ran into is the event by event output is not well-formed. You can simply go ./s2protocol.py options replay > document.json. Do you think this is important or that the consumer should reformat the output?

**Comment by breath20** [comment]
I use a slightly different version than what is in this commit, I have 
`s = json.dumps(event, separators=(',', ':'), encoding='ISO-8859-1')`

And I also just changed it so it always outputs json since that's my use case. 

I am not a huge fan of python so I export the replay and import it into php. after I import it into php I lean on mostly the _events of each of the objects but a few of them don't have one so I end up setting one based on what I can find. 

To me the option seems straight forward, and I do expect that the consumer would reformat the output (I do 👍on sc2replaystats )

**Comment by Artmann** [comment]
@jrepp Thanks for taking the time to reply. I've been using the json output in an application not writtern in python, so formating has not been an issue. It's seems like breath20 has taken and similar approach trying to use s2protocol in an existing application.

**Comment by breath20** [comment]
I do recall fighting some json formatting problems way back (its been like 3 years since I have had to change s2protocol on my side). I know changing the encoding solved some localization problems I was having with KR replays. I don't recall why I added the separators......

**Comment by jrepp** [comment]
It was perhaps to get the JSON output looking nicer?

There are pros and cons to filtering the JSON events through PrettyPrinter

Pros: 
- Event delimiters (single quote)
- Simpler to implement

Cons: 
- Harder to read
- Extra cruft in stream
- Slower
- Potential for weird Python string shenanigans?

I did a merge of the JSON changes and setup a more general filter chain in the CLI so you just opt into the output/stats required by the command line arguments. 

https://github.com/jrepp/s2protocol/tree/json-merge

I'm going to read up on what other people are doing for very long JSON event streams. It would be good to use a more standard approach.

I think encoding is something that probably deserves a little bit more thought as well. JSON supports Unicode in the spec (json.org) through the usage of escape characters so that a JSON document can be transmitted as ASCII and compatible with the lowest common denominator of HTTP (AFAIK).  I think using JSON as a textual output has a lot of benefits for connecting command line tools as well because of this.

The problems people are seeing may occur when you decode a JSON document into a python object and then pretty print that python object. Python 2 and 3 represent strings differently and both have special considerations when dealing with Unicode. Sometimes you'll see this as u'my string' I think.

My initial thoughts are that the CLI should ouput JSON text directly, encoded as an ASCII JSON document with no extra conversion. The consuming language should then be able to convert strings containing UTF  according to the JSON spec. ISO-8859-1 is a default ASCII encoding for HTTP and covers the requirements for JSON so I think that should work great.

This should allow things like s2protocol.py | csharptool.exe etc.

Thanks for the feedback. I know this is a small part of an overall larger chain of things and I want to be sensitive to breaking things that have been working for a long time.

I'll make sure to stage the release of these changes - for SC2 3.10 and 3.11 I'll do a dual release by hand.. basically business as usual for the protocol<ver>.py update in master but then I hand merge in a staging branch. This gives everyone using this library a good amount of time to test the changes.

**Comment by breath20** [comment]
Speed is very important to me, the python export is 98% of my time spend on my processing job, so anyway we can speed it up (more noticeable on longer replays and team games ) would be huge for me.

**Comment by jrepp** [comment]
This is now available here: https://github.com/Blizzard/s2protocol/tree/dev

There are definitely more optimizations that can be made, I will look into that. Performance should be slightly improved on this new dev branch.

Try the new --ndjson option for the [newline delimited json](http://ndjson.org/) output

**Pull request closed without merging**
